[workspace]
resolver = "2"
members = [
    "crates/vertex-core",
    "crates/vertex-renderer",
    "crates/vertex-editor",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/hunterkritik-byte/Vertex-Engine"

[workspace.dependencies]
winit = "0.30"
